name: Publish to NPM with Semantic Release

on:
  push:
    branches:
      - test-workflow
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: '20'
      
      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release